### ISSUE TITLE
using it for custom questions?

### ISSUE THREAD

**Issue by bharatv007** [stanfordnlp/mac-network#18]
Hey,

After training it, I want to use the model to take custom questions given some image from the dataset.

I am not sure if I am right, but it feel like the code does not have that mode. Particularly, that it loads the json file for val,test and re initializes the embedding. Also vocab file takes quite a while to load from .pkl files.
Can you please help me with this?

**Comment by dorarad** [comment]
Hi, sure! I'll be happy if you can please provide me a bit further information on your use case - do you need to evaluate "online" questions, i.e. in an interactive mode? or to evaluate on a new file? 

For the first case, the code currently supports an interactive case through `--interactive`, so that you can specify an image id and then type a question. (Though the interface is currently very basic and could use some improvements).

For the second case, you're right that the code currently doesn't support that as-is, there has to be a small change to allow a custom file to be uploaded rather than a pre-set split. I'll be happy to add support for that! (hopefully won't take more than a few days since it's a bit busy time for me right now in the quarter, but will try to update it as soon as I can!)

**Comment by bharatv007** [comment]
Hi,

Thanks for getting back to me. 
I do not see any interactive mode?
I may be overlooking something. I would like to evaluate online questions. So if you can let me know about the interactive mode, then I can start there and that would help me.

Thanks!

**Comment by dorarad** [comment]
Hi, yea it's in the GQA branch:  `--interactive` to make it work, and then `--interactiveTier` to choose the image dataset you ask questions about (train/val/test). It currently doesn't support other images because the model needs pretrained extracted features from each image, which the model gets as a frozen input.

If I remember correctly you also have to make sure you _don't_ pass the standard `--train` / `--test` flags so that it will move right away to the interactive stage, and also make sure to add `-r` (or `--restoreEpoch`) to make it load the trained weights.

Please let me know if you have any questions or suggestions about this flag! (I haven't added it to the master branch because I would still like to improve it a little bit more before)

**Comment by bharatv007** [comment]
I went through the interactive part of GQA and made a few more changes to get what I wanted.
Thanks for the help.

**Comment by dorarad** [comment]
Awesome! if you'd like to submit a PR for the changes you've made the would be great, and in any case happy that it helped you!
