### ISSUE TITLE
questions are not related to images

### ISSUE THREAD

**Issue by ziyanyang** [stanfordnlp/mac-network#24]
Hi,

I just trained a baseline(LSTM+CNN) and checked the predictions, but I figured out in the generated json file, several images have questions not corresponding to the objects in them. For example, [this image](http://vision.cs.virginia.edu/data/gqa/data/images/2359959.jpg)(id:2359959) has questions: 
Is there a sandwich in the image?
What kind of food is it?
Is the sandwich on the right?
Are there any clocks or flags?

But actually there is no food in the image.

Also, in [this image](http://vision.cs.virginia.edu/data/gqa/data/images/2371593.jpg)(id:2371593) the question is:
In which part of the picture is the cat, the bottom or the top?

But actually the object is a person.

The questions are automatically generated for the images using scene graph, and I feel confused about in which step these mistakes may happen?

Thanks!

**Comment by dorarad** [comment]
Hi there! Thanks a lot for pointing that out! 

In this specific case you mention it definitely sounds to me like it might be due to a bug that I made that led to those wrong questions so will look into it and get back to you about these!

More generally, the questions are generated using a cleaner version of visual genome scene graphs https://visualgenome.org/ and so we are tied in our our correctness to the level of correctness in visual genome annotations (which collected and verified by people and was cleaned further for this project). Sometimes even though we clean visual genome scene graphs there might be rare cases where an error in the graph propagates to the questions themselves, although in this case it sounds to me that for the image you mentioned it's just due to a bug rather than inaccurate scene graphs. 

Finally, _please note that we evaluated several thousands questions that were sampled at random with human experiments and got a bit more than 89% accuracy_ to confirm the reliability of questions over images. 

I will get back to you about these questions and what led to this error!

**Comment by dorarad** [comment]
Alright I checked there was an annotation error in visual genome that led to this case: the objects that were annotated for 2359959 are: flower, leaves, basket, ground, orchid, sandwich, trunk and for 2371593 are: tie, piercing, earrings, clothes, jewelry, chains, cat, lip, ear, nose, eye, arm. I will remove these wrong annotations to solve this and will update the dataset accordingly.

This case should be very rare - You can browse through visual genome https://visualgenome.org/VGViz/explore to see examples of graph annotations. They are correct in almost all especially after the further clean-up and whenever they're accurate the generated questions match to that. I'm sorry for these errors, and please let me know if you have any other questions! :)
