### ISSUE TITLE
Issue with the repo link using git clone

### ISSUE THREAD

**Issue by akshay-sharma1995** [stanfordnlp/mac-network#37]
Hey, I think the download link for the repo has some issues. If i clone the directory using [https://github.com/stanfordnlp/mac-network.git](url) through git clone, all the files are not downloaded. The download zip option seems to be working fine though.

**Comment by dorarad** [comment]
I tried to do `git clone https://github.com/stanfordnlp/mac-network.git` now in a clean environment and it worked fine for me. I believe probably the issue you experience is due to some general git settings rather than specifically with this repo particularly? Please try from a clean environment or let me know what error do you get!

**Comment by akshay-sharma1995** [comment]
I was trying to clone the repo for the GQA challenge, from [https://github.com/stanfordnlp/mac-network/tree/gqa](url). The issue is the "Clone or download" button displays the link for the original mac-network repo [https://github.com/stanfordnlp/mac-network.git](url) and not the GQA one.

**Comment by dorarad** [comment]
That sounds fine, after cloning you just have to also do `git checkout gqa` and you'll be on the right branch!

**Comment by akshay-sharma1995** [comment]
I did not know that. It works. Thanks a lot, and sorry for the confusion.
