### ISSUE TITLE
consistency, validity, and plausibility in GQA

### ISSUE THREAD

**Issue by dami23** [stanfordnlp/mac-network#43]
Dear @dorarad, I encounter several problems when I run a project on GQA. Could you please help me?
1. Consistency evaluation. Which .json should be used to evaluate the consistency? I used testdev_balanced_questions.json, but an error occurred, ['2062326'] key error. I found this id is included in the testdev_all_questions.json.

2. Validity and Plausibility. According to the provided eval.py, the json file should be the train_choices.json and val_choices.json.  The KeyError: '201497576' will be triggered in code line: valid = belongs(predicted, choices[qid]["valid"], question). And, the two files have no ["valid"] and ["plausible"].

Could you please help me to solve these problems? Thank you

**Comment by dorarad** [comment]
Hi Dami,
For consistency, an all questions file should be used - the balanced set is just a sample out of all of the questions, while in order to check for consistency there's a need to go over all the questions including equivalent ones to be able to compute this metric.

For validity/plausibility last time I checked it all worked, will check again given the info you describe and get back to you!

**Comment by dami23** [comment]
Hi dorarad, thank you for your reply. For consistency, you mean the testdev_all_questions.json should be used? And only the testdev_all_questions.json include ['2062326'].

For validity/plausibility, I have checked on the all .json files, no ["valid"] and ["plausible"]. Waiting for your reply. Thank you!

**Comment by dorarad** [comment]
Hi yea I mean the testdev_all_questions.json, alright will check and update you about the validity/plausibility!

**Comment by dami23** [comment]
Besides, img 2316942 and 2417331 have no frcn feats in the provided .h5 files.

**Comment by dami23** [comment]
@dorarad Hi, dorarad. Could you please help me to solve the error for validating the Validity and Plausibility? Thank you!

**Comment by dorarad** [comment]
Sure really hope to get to it today!

**Comment by dorarad** [comment]
sorry for the delay getting into it right now will update soon!

**Comment by dorarad** [comment]
Alright checked that! So the thing is for the testdev split we only provide the questions and answers (without the additional information like scene graphs or choices). In order to evaluate all metrics for testdev or test you need to submit to the challenge website and then will get the scores. Alternatively, it's also possible to evaluate over train or val splits for which all the supervised info is provided.

For the images - we provide features only for images for which there are questions in GQA rather than for all images in Visual Genome which is why the images 2316942 and 2417331 are not in the features file.

Hope that helps! please let me know if you have any additional questions!
We plan to have a new challenge starting in a couple of days that will go until late May and will also introduce in the next few weeks an updated test set. Hope that you may be interested in participating! :)
